/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jadha
 */

import javax.swing.JOptionPane;
public class FastCash extends javax.swing.JFrame {
static int amount;
static int pinnumber;
    /**
     * Creates new form FastCash
     */
    public FastCash(int amount,int pinnumber) {
        this.amount = amount;
        this.pinnumber = pinnumber;
        
        
        initComponents();
        txtbal.setText(amount+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblwithdraw = new javax.swing.JLabel();
        btn100 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn1000 = new javax.swing.JButton();
        btn5000 = new javax.swing.JButton();
        btn200 = new javax.swing.JButton();
        btn10000 = new javax.swing.JButton();
        lblbalance = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        txtbal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblwithdraw.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblwithdraw.setText("Select the amount for Withrawl");

        btn100.setBackground(new java.awt.Color(0, 0, 0));
        btn100.setForeground(new java.awt.Color(255, 255, 255));
        btn100.setText("100 RS");
        btn100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn100ActionPerformed(evt);
            }
        });

        btn500.setBackground(new java.awt.Color(0, 0, 0));
        btn500.setForeground(new java.awt.Color(255, 255, 255));
        btn500.setText("500 Rs");
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });

        btn1000.setBackground(new java.awt.Color(0, 0, 0));
        btn1000.setForeground(new java.awt.Color(255, 255, 255));
        btn1000.setText("1000 Rs");
        btn1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1000ActionPerformed(evt);
            }
        });

        btn5000.setBackground(new java.awt.Color(0, 0, 0));
        btn5000.setForeground(new java.awt.Color(255, 255, 255));
        btn5000.setText("5000 Rs");
        btn5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5000ActionPerformed(evt);
            }
        });

        btn200.setBackground(new java.awt.Color(0, 0, 0));
        btn200.setForeground(new java.awt.Color(255, 255, 255));
        btn200.setText("200 Rs");
        btn200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn200ActionPerformed(evt);
            }
        });

        btn10000.setBackground(new java.awt.Color(0, 0, 0));
        btn10000.setForeground(new java.awt.Color(255, 255, 255));
        btn10000.setText("10000 Rs");
        btn10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn10000ActionPerformed(evt);
            }
        });

        lblbalance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblbalance.setText("Balance");

        btnexit.setBackground(new java.awt.Color(0, 0, 0));
        btnexit.setForeground(new java.awt.Color(255, 255, 255));
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblwithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn100, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(btn500, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn5000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn10000)
                            .addComponent(btn200, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                            .addComponent(btn1000, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(74, 74, 74))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(lblbalance)
                        .addGap(18, 18, 18)
                        .addComponent(txtbal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblwithdraw)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblbalance)
                    .addComponent(txtbal, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn200)
                    .addComponent(btn100))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn500)
                    .addComponent(btn1000))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn5000)
                    .addComponent(btn10000))
                .addGap(18, 18, 18)
                .addComponent(btnexit)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5000ActionPerformed
        if(amount<5000){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 5000;
            JOptionPane.showMessageDialog(this,"amount withdrawn successfully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn5000ActionPerformed

    private void btn100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100ActionPerformed
        
        if(amount<100){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 100;
            JOptionPane.showMessageDialog(this,"amount withdrawn succefffully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn100ActionPerformed

    private void btn200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn200ActionPerformed
        // TODO add your handling code here:
        if(amount<200){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 200;
            JOptionPane.showMessageDialog(this,"amount withdrawn succefffully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn200ActionPerformed

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        // TODO add your handling code here:
        if(amount<500){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 500;
            JOptionPane.showMessageDialog(this,"amount withdrawn succefffully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn500ActionPerformed

    private void btn1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000ActionPerformed
        // TODO add your handling code here:
        if(amount<1000){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 1000;
            JOptionPane.showMessageDialog(this,"amount withdrawn succefffully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn1000ActionPerformed

    private void btn10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10000ActionPerformed
        // TODO add your handling code here:
        if(amount<10000){
            JOptionPane.showMessageDialog(this,"Not enough balance amount");
        }else{
            amount = amount - 10000;
            JOptionPane.showMessageDialog(this,"amount withdrawn succefffully");
            setVisible(false);
            new Transaction(amount,pinnumber).setVisible(true);
        }
    }//GEN-LAST:event_btn10000ActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        setVisible(false);
        new Transaction(amount,pinnumber).setVisible(true);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FastCash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FastCash(amount,pinnumber).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn100;
    private javax.swing.JButton btn1000;
    private javax.swing.JButton btn10000;
    private javax.swing.JButton btn200;
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn5000;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel lblbalance;
    private javax.swing.JLabel lblwithdraw;
    private javax.swing.JLabel txtbal;
    // End of variables declaration//GEN-END:variables
}
